/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.Tracker;
import Model.Peer;
import Model.enumStateFile;
import Model.enumStateUser;
import Negocio.MixPot;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author williambaquero
 */
public class Principal extends javax.swing.JFrame {
    
    private final String SI_EXISTE = "Encontrado";
    private final String NO_EXISTE = "No encontrado";
    private final String CREADO = "Archivo generado";
    private final int TAM_ESTANDAR = 8;
    
    private List<File> listaArchivos = new ArrayList<>();
    private HashMap<String, List<File>> hashMapArchivos = new HashMap<>();
    private Tracker tracker;

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.tracker = new Tracker(this);
        initComponents();
        btnSubir.setEnabled(false);
        centreWindow(Principal.this);
        clearTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDistri = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnDescargar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDownloads = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JToggleButton();
        btnSubir = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFiles = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        nameGenerate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivos");
        jLabel1.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setEnabled(false);

        btnDescargar.setText("Descargar");
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });

        tableDownloads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Estado", "Generado en"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDownloads);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDescargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDescargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        PanelDistri.addTab("Descargas", jPanel1);

        jLabel2.setText("Ruta Archivo");

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        btnSubir.setText("Subir");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        tableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre", "Existencia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableFiles);

        jLabel3.setText("Nombre archivo a generar: ");

        nameGenerate.setText("-");

        jLabel5.setText("Archivo seleccionado: ");

        labelSelected.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(nameGenerate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(50, 50, 50)
                        .addComponent(labelSelected)))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnExaminar)
                    .addComponent(btnSubir))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelSelected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameGenerate))
                .addGap(0, 51, Short.MAX_VALUE))
        );

        PanelDistri.addTab("Subida", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDistri)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelDistri, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        System.out.println(hashMapArchivos.keySet());
        for (int i = 0; i < hashMapArchivos.get(nameGenerate.getText()).size(); i++) {
            System.out.println(hashMapArchivos.get(nameGenerate.getText()).get(i).getName());
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed
        clearTables();
        selectFile();
    }//GEN-LAST:event_btnExaminarActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        try {
            formarArchivoGenerado();
        } catch (IOException ex) {
            System.out.println("No se pudo descargar el archivo" + ex);
        }
    }//GEN-LAST:event_btnDescargarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }
    
    //=========================================================================
    //   METODOS DE APOYO
    //=========================================================================
    
    //Centrar la pantalla
    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }
    
    //Limpiar información sucia de las tablas
    public void clearTables (){
        DefaultTableModel model = (DefaultTableModel) tableFiles.getModel();
        for (int i = 0; i < model.getRowCount() ; i++) {
            model.removeRow(i);
        }
        
        model = (DefaultTableModel) tableDownloads.getModel();
        for (int i = 0; i < model.getRowCount() ; i++) {
            model.removeRow(i);
        }
        model.setRowCount(0);
    }
    
    //Escoger un archivo 
    public void selectFile() {
        JFileChooser chooser = new JFileChooser("./");
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            
            try {
                readFile(f);
            } catch (IOException ex) {
                System.out.println("Problema leyendo el arvhivo");
            }
            
        } else {
            // user changed their mind
        }
    }
    
    //Leer archivo
    private void readFile(File file) throws FileNotFoundException, IOException{
        
        listaArchivos.clear();
        hashMapArchivos.clear();
        
        BufferedReader br = new BufferedReader(new FileReader(file.getName()));
        DefaultTableModel model = (DefaultTableModel) tableFiles.getModel();
        model.setRowCount(0);
        labelSelected.setText(file.getName());
        try {
            StringBuilder sb = new StringBuilder();
            String line = br.readLine();
            int countLine = 0;

            while (line != null) {
                if(countLine++==0)nameGenerate.setText(line + ".txt");
                sb.append(line);
                sb.append("\n");
                line = br.readLine();
                if (line!=null) {
                    //System.out.println(line);
                    File f = new File("./"+line+".txt");
                    if(f.exists() && !f.isDirectory()) { 
                        model.addRow(new Object[]{line, SI_EXISTE});
                    }else{
                        model.addRow(new Object[]{line, NO_EXISTE});
                    }
                    listaArchivos.add(f);
                    hashMapArchivos.put(nameGenerate.getText(), listaArchivos);
                }
            }
            
            btnSubir.setEnabled(isSubidaOk() ? true : false);
            
            String completo =  sb.toString();
            
        } finally {
            br.close();
        }    
    }
    
    //Comprobar si todos los archivos dentro del archivo descriptor existen
    public boolean isSubidaOk(){
        DefaultTableModel model = (DefaultTableModel) tableFiles.getModel(); 
        for (int i = 0; i < model.getRowCount(); i++) if (model.getValueAt(i, 1).equals(NO_EXISTE)){ hashMapArchivos.clear(); return false;};
        
        return true;
    }
    
    //Generar el archivo para ser descargado 
    public void formarArchivoGenerado() throws IOException{
        
        String nameFile = NO_EXISTE;

        for(Map.Entry<String, List<File>> entry : hashMapArchivos.entrySet()) {
            String key = entry.getKey();
            nameFile = key;
        }
        
        if (!nameFile.equals(NO_EXISTE)) {
            List<String> lines = mixFiles(nameFile);
            String[] strarray = new String[lines.size()];
            lines.toArray(strarray);
            lines = Arrays.asList(strarray);
            Path file = Paths.get(nameFile);
            Files.write(file, lines, Charset.forName("UTF-8"));
            Date dNow = new Date( );
            SimpleDateFormat ft = new SimpleDateFormat ("hh:mm:ss a");
            DefaultTableModel model = (DefaultTableModel) tableDownloads.getModel(); 
            model.addRow(new Object[]{nameFile, CREADO,ft.format(dNow)});
            
            System.out.println(" -> Archivo creado con éxito!");
            
        }else{
            System.err.println("No existe fuente para descargar archivos.");
            System.err.println("(Ya probaste subir archivos primero?)");
        }
        

    }
    
    //Con los archivos existentes generar el nuevo
    public List<String> mixFiles(String nameFile) throws FileNotFoundException, IOException{
        
        List<MixPot> listaMixer = new ArrayList<>();
        List<String> lineasArchivos = new ArrayList<>();
        int tamToMix = hashMapArchivos.get(nameFile).size();
        
        for (int i = 0; i < TAM_ESTANDAR ; i++) {
            int elElegido = (int) (Math.random() * tamToMix) + 0;
            MixPot mix = new MixPot(i, hashMapArchivos.get(nameFile).get(elElegido));
            listaMixer.add(mix);
        }
        
        
        for (int i = 0; i < TAM_ESTANDAR ; i++) {
            
            try(BufferedReader br = new BufferedReader(new FileReader(listaMixer.get(i).getArchivo().getName()))) {
                int contador = 0;
                for(String line; (line = br.readLine()) != null; ) {
                    
                    if (listaMixer.get(i).getLinea() == contador) {
                        String agregar = line;
                        lineasArchivos.add(agregar);
                    }
                    
                    contador++;
                    
                }
                // line is not visible here.
            }
            
        }
                
        return lineasArchivos;
    }
    
    public void updatePeers(List<Peer> swarm) {

        //JOptionPane.showMessageDialog(this, swarm.size());
        
//        vaciarModelo(this.modelPeers);
//        
//        for (Peer p : swarm) {           
//            String [] datos={p.getIp(),""};
//            this.modelPeers.addRow(datos);
//        }

    }
    
    public void updateFiles(Map<String, Map<Peer,enumStateUser> > mapFiles) {

        //JOptionPane.showMessageDialog(this, swarm.size());
        
//        vaciarModelo(this.modelFiles);
//        
//        for (Map.Entry<String, Map<Peer,enumStateUser> > entry : mapFiles.entrySet()) {
//            
//            for (Map.Entry<Peer,enumStateUser> entryFile : entry.getValue().entrySet()) {
//                String [] datos={entry.getKey(),entryFile.getKey().getIp(),entryFile.getValue().toString()};
//                this.modelFiles.addRow(datos);
//            }
//            
//        }
    
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelDistri;
    private javax.swing.JButton btnDescargar;
    private javax.swing.JToggleButton btnExaminar;
    private javax.swing.JToggleButton btnSubir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelSelected;
    private javax.swing.JLabel nameGenerate;
    private javax.swing.JTable tableDownloads;
    private javax.swing.JTable tableFiles;
    // End of variables declaration//GEN-END:variables
}
